// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sarxzcnslwsxofdndmbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhcnh6Y25zbHdzeG9mZG5kbWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDU0MTQsImV4cCI6MjA3NDEyMTQxNH0.iPIrAM7Zml5tvTKi7-U77uNhBdWuv38T9AFe8xdSxIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});